/* tslint:disable */
/* eslint-disable */
/**
 * Geoguess Lite
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
/**
 *
 * @export
 * @interface CreateDailyScoreRequest
 */
export interface CreateDailyScoreRequest {
  /**
   *
   * @type {number}
   * @memberof CreateDailyScoreRequest
   */
  score: number
  /**
   *
   * @type {number}
   * @memberof CreateDailyScoreRequest
   */
  distance: number
  /**
   *
   * @type {number}
   * @memberof CreateDailyScoreRequest
   */
  timeTaken: number
}

/**
 * Check if a given object implements the CreateDailyScoreRequest interface.
 */
export function instanceOfCreateDailyScoreRequest(value: object): value is CreateDailyScoreRequest {
  if (!('score' in value) || value['score'] === undefined) return false
  if (!('distance' in value) || value['distance'] === undefined) return false
  if (!('timeTaken' in value) || value['timeTaken'] === undefined) return false
  return true
}

export function CreateDailyScoreRequestFromJSON(json: any): CreateDailyScoreRequest {
  return CreateDailyScoreRequestFromJSONTyped(json, false)
}

export function CreateDailyScoreRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CreateDailyScoreRequest {
  if (json == null) {
    return json
  }
  return {
    score: json['score'],
    distance: json['distance'],
    timeTaken: json['time_taken'],
  }
}

export function CreateDailyScoreRequestToJSON(json: any): CreateDailyScoreRequest {
  return CreateDailyScoreRequestToJSONTyped(json, false)
}

export function CreateDailyScoreRequestToJSONTyped(
  value?: CreateDailyScoreRequest | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    score: value['score'],
    distance: value['distance'],
    time_taken: value['timeTaken'],
  }
}
