/* tslint:disable */
/* eslint-disable */
/**
 * Geoguess Lite
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
/**
 *
 * @export
 * @interface CreateMultiplayerRounds200Response
 */
export interface CreateMultiplayerRounds200Response {
  /**
   *
   * @type {string}
   * @memberof CreateMultiplayerRounds200Response
   */
  message?: string
}

/**
 * Check if a given object implements the CreateMultiplayerRounds200Response interface.
 */
export function instanceOfCreateMultiplayerRounds200Response(
  value: object,
): value is CreateMultiplayerRounds200Response {
  return true
}

export function CreateMultiplayerRounds200ResponseFromJSON(
  json: any,
): CreateMultiplayerRounds200Response {
  return CreateMultiplayerRounds200ResponseFromJSONTyped(json, false)
}

export function CreateMultiplayerRounds200ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CreateMultiplayerRounds200Response {
  if (json == null) {
    return json
  }
  return {
    message: json['message'] == null ? undefined : json['message'],
  }
}

export function CreateMultiplayerRounds200ResponseToJSON(
  json: any,
): CreateMultiplayerRounds200Response {
  return CreateMultiplayerRounds200ResponseToJSONTyped(json, false)
}

export function CreateMultiplayerRounds200ResponseToJSONTyped(
  value?: CreateMultiplayerRounds200Response | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    message: value['message'],
  }
}
