/* tslint:disable */
/* eslint-disable */
/**
 * Geoguess Lite
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
/**
 *
 * @export
 * @interface CreateMultiplayerRoundsRequest
 */
export interface CreateMultiplayerRoundsRequest {
  /**
   *
   * @type {string}
   * @memberof CreateMultiplayerRoundsRequest
   */
  roomId: string
}

/**
 * Check if a given object implements the CreateMultiplayerRoundsRequest interface.
 */
export function instanceOfCreateMultiplayerRoundsRequest(
  value: object,
): value is CreateMultiplayerRoundsRequest {
  if (!('roomId' in value) || value['roomId'] === undefined) return false
  return true
}

export function CreateMultiplayerRoundsRequestFromJSON(json: any): CreateMultiplayerRoundsRequest {
  return CreateMultiplayerRoundsRequestFromJSONTyped(json, false)
}

export function CreateMultiplayerRoundsRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CreateMultiplayerRoundsRequest {
  if (json == null) {
    return json
  }
  return {
    roomId: json['room_id'],
  }
}

export function CreateMultiplayerRoundsRequestToJSON(json: any): CreateMultiplayerRoundsRequest {
  return CreateMultiplayerRoundsRequestToJSONTyped(json, false)
}

export function CreateMultiplayerRoundsRequestToJSONTyped(
  value?: CreateMultiplayerRoundsRequest | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    room_id: value['roomId'],
  }
}
