/* tslint:disable */
/* eslint-disable */
/**
 * Geoguess Lite
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
/**
 *
 * @export
 * @interface DailyScore
 */
export interface DailyScore {
  /**
   *
   * @type {string}
   * @memberof DailyScore
   */
  id: string
  /**
   *
   * @type {string}
   * @memberof DailyScore
   */
  userId: string
  /**
   *
   * @type {number}
   * @memberof DailyScore
   */
  score: number
  /**
   *
   * @type {number}
   * @memberof DailyScore
   */
  distance: number
  /**
   *
   * @type {number}
   * @memberof DailyScore
   */
  timeTaken: number
  /**
   *
   * @type {string}
   * @memberof DailyScore
   */
  name: string
  /**
   *
   * @type {string}
   * @memberof DailyScore
   */
  avatarEmoji: string
  /**
   *
   * @type {string}
   * @memberof DailyScore
   */
  avatarBg: string
}

/**
 * Check if a given object implements the DailyScore interface.
 */
export function instanceOfDailyScore(value: object): value is DailyScore {
  if (!('id' in value) || value['id'] === undefined) return false
  if (!('userId' in value) || value['userId'] === undefined) return false
  if (!('score' in value) || value['score'] === undefined) return false
  if (!('distance' in value) || value['distance'] === undefined) return false
  if (!('timeTaken' in value) || value['timeTaken'] === undefined) return false
  if (!('name' in value) || value['name'] === undefined) return false
  if (!('avatarEmoji' in value) || value['avatarEmoji'] === undefined) return false
  if (!('avatarBg' in value) || value['avatarBg'] === undefined) return false
  return true
}

export function DailyScoreFromJSON(json: any): DailyScore {
  return DailyScoreFromJSONTyped(json, false)
}

export function DailyScoreFromJSONTyped(json: any, ignoreDiscriminator: boolean): DailyScore {
  if (json == null) {
    return json
  }
  return {
    id: json['id'],
    userId: json['user_id'],
    score: json['score'],
    distance: json['distance'],
    timeTaken: json['time_taken'],
    name: json['name'],
    avatarEmoji: json['avatar_emoji'],
    avatarBg: json['avatar_bg'],
  }
}

export function DailyScoreToJSON(json: any): DailyScore {
  return DailyScoreToJSONTyped(json, false)
}

export function DailyScoreToJSONTyped(
  value?: DailyScore | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    id: value['id'],
    user_id: value['userId'],
    score: value['score'],
    distance: value['distance'],
    time_taken: value['timeTaken'],
    name: value['name'],
    avatar_emoji: value['avatarEmoji'],
    avatar_bg: value['avatarBg'],
  }
}
