/* tslint:disable */
/* eslint-disable */
/**
 * Geoguess Lite
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
import type { GetTodayChallenge200ResponseRoundsInner } from './GetTodayChallenge200ResponseRoundsInner'
import {
  GetTodayChallenge200ResponseRoundsInnerFromJSON,
  GetTodayChallenge200ResponseRoundsInnerFromJSONTyped,
  GetTodayChallenge200ResponseRoundsInnerToJSON,
  GetTodayChallenge200ResponseRoundsInnerToJSONTyped,
} from './GetTodayChallenge200ResponseRoundsInner'

/**
 *
 * @export
 * @interface DailyChallenge
 */
export interface DailyChallenge {
  /**
   *
   * @type {Date}
   * @memberof DailyChallenge
   */
  date: Date
  /**
   *
   * @type {Array<GetTodayChallenge200ResponseRoundsInner>}
   * @memberof DailyChallenge
   */
  rounds: Array<GetTodayChallenge200ResponseRoundsInner>
}

/**
 * Check if a given object implements the DailyChallenge interface.
 */
export function instanceOfDailyChallenge(value: object): value is DailyChallenge {
  if (!('date' in value) || value['date'] === undefined) return false
  if (!('rounds' in value) || value['rounds'] === undefined) return false
  return true
}

export function DailyChallengeFromJSON(json: any): DailyChallenge {
  return DailyChallengeFromJSONTyped(json, false)
}

export function DailyChallengeFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): DailyChallenge {
  if (json == null) {
    return json
  }
  return {
    date: new Date(json['date']),
    rounds: (json['rounds'] as Array<any>).map(GetTodayChallenge200ResponseRoundsInnerFromJSON),
  }
}

export function DailyChallengeToJSON(json: any): DailyChallenge {
  return DailyChallengeToJSONTyped(json, false)
}

export function DailyChallengeToJSONTyped(
  value?: DailyChallenge | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    date: value['date'].toISOString().substring(0, 10),
    rounds: (value['rounds'] as Array<any>).map(GetTodayChallenge200ResponseRoundsInnerToJSON),
  }
}
