/* tslint:disable */
/* eslint-disable */
/**
 * Geoguess Lite
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
import type { GetImages200ResponseImagesInner } from './GetImages200ResponseImagesInner'
import {
  GetImages200ResponseImagesInnerFromJSON,
  GetImages200ResponseImagesInnerFromJSONTyped,
  GetImages200ResponseImagesInnerToJSON,
  GetImages200ResponseImagesInnerToJSONTyped,
} from './GetImages200ResponseImagesInner'

/**
 *
 * @export
 * @interface GetImages200Response
 */
export interface GetImages200Response {
  /**
   *
   * @type {Array<GetImages200ResponseImagesInner>}
   * @memberof GetImages200Response
   */
  images: Array<GetImages200ResponseImagesInner>
}

/**
 * Check if a given object implements the GetImages200Response interface.
 */
export function instanceOfGetImages200Response(value: object): value is GetImages200Response {
  if (!('images' in value) || value['images'] === undefined) return false
  return true
}

export function GetImages200ResponseFromJSON(json: any): GetImages200Response {
  return GetImages200ResponseFromJSONTyped(json, false)
}

export function GetImages200ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): GetImages200Response {
  if (json == null) {
    return json
  }
  return {
    images: (json['images'] as Array<any>).map(GetImages200ResponseImagesInnerFromJSON),
  }
}

export function GetImages200ResponseToJSON(json: any): GetImages200Response {
  return GetImages200ResponseToJSONTyped(json, false)
}

export function GetImages200ResponseToJSONTyped(
  value?: GetImages200Response | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    images: (value['images'] as Array<any>).map(GetImages200ResponseImagesInnerToJSON),
  }
}
