/* tslint:disable */
/* eslint-disable */
/**
 * Geoguess Lite
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
/**
 *
 * @export
 * @interface GetImages200ResponseImagesInner
 */
export interface GetImages200ResponseImagesInner {
  /**
   *
   * @type {string}
   * @memberof GetImages200ResponseImagesInner
   */
  id: string
  /**
   *
   * @type {boolean}
   * @memberof GetImages200ResponseImagesInner
   */
  isPano: boolean
}

/**
 * Check if a given object implements the GetImages200ResponseImagesInner interface.
 */
export function instanceOfGetImages200ResponseImagesInner(
  value: object,
): value is GetImages200ResponseImagesInner {
  if (!('id' in value) || value['id'] === undefined) return false
  if (!('isPano' in value) || value['isPano'] === undefined) return false
  return true
}

export function GetImages200ResponseImagesInnerFromJSON(
  json: any,
): GetImages200ResponseImagesInner {
  return GetImages200ResponseImagesInnerFromJSONTyped(json, false)
}

export function GetImages200ResponseImagesInnerFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): GetImages200ResponseImagesInner {
  if (json == null) {
    return json
  }
  return {
    id: json['id'],
    isPano: json['is_pano'],
  }
}

export function GetImages200ResponseImagesInnerToJSON(json: any): GetImages200ResponseImagesInner {
  return GetImages200ResponseImagesInnerToJSONTyped(json, false)
}

export function GetImages200ResponseImagesInnerToJSONTyped(
  value?: GetImages200ResponseImagesInner | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    id: value['id'],
    is_pano: value['isPano'],
  }
}
