/* tslint:disable */
/* eslint-disable */
/**
 * Geoguess Lite
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetMeRequest
 */
export interface GetMeRequest {
    /**
     * 
     * @type {string}
     * @memberof GetMeRequest
     */
    name: string;
}

/**
 * Check if a given object implements the GetMeRequest interface.
 */
export function instanceOfGetMeRequest(value: object): value is GetMeRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function GetMeRequestFromJSON(json: any): GetMeRequest {
    return GetMeRequestFromJSONTyped(json, false);
}

export function GetMeRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetMeRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
    };
}

export function GetMeRequestToJSON(json: any): GetMeRequest {
    return GetMeRequestToJSONTyped(json, false);
}

export function GetMeRequestToJSONTyped(value?: GetMeRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
    };
}

