/* tslint:disable */
/* eslint-disable */
/**
 * Geoguess Lite
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
/**
 *
 * @export
 * @interface GetMe200Response
 */
export interface GetMe200Response {
  /**
   *
   * @type {string}
   * @memberof GetMe200Response
   */
  id: string
  /**
   *
   * @type {string}
   * @memberof GetMe200Response
   */
  name: string
  /**
   *
   * @type {string}
   * @memberof GetMe200Response
   */
  avatarEmoji: string
  /**
   *
   * @type {string}
   * @memberof GetMe200Response
   */
  avatarBg: string
  /**
   *
   * @type {number}
   * @memberof GetMe200Response
   */
  gamesPlayed: number
  /**
   *
   * @type {number}
   * @memberof GetMe200Response
   */
  bestScore: number
  /**
   *
   * @type {number}
   * @memberof GetMe200Response
   */
  averageScore: number
  /**
   * Whether the user has played today's daily challenge
   * @type {boolean}
   * @memberof GetMe200Response
   */
  hasPlayedDailyChallenge: boolean
  /**
   * Preferred distance unit
   * @type {string}
   * @memberof GetMe200Response
   */
  distanceUnit: GetMe200ResponseDistanceUnitEnum
}

/**
 * @export
 */
export const GetMe200ResponseDistanceUnitEnum = {
  Km: 'km',
  Mile: 'mile',
} as const
export type GetMe200ResponseDistanceUnitEnum =
  (typeof GetMe200ResponseDistanceUnitEnum)[keyof typeof GetMe200ResponseDistanceUnitEnum]

/**
 * Check if a given object implements the GetMe200Response interface.
 */
export function instanceOfGetMe200Response(value: object): value is GetMe200Response {
  if (!('id' in value) || value['id'] === undefined) return false
  if (!('name' in value) || value['name'] === undefined) return false
  if (!('avatarEmoji' in value) || value['avatarEmoji'] === undefined) return false
  if (!('avatarBg' in value) || value['avatarBg'] === undefined) return false
  if (!('gamesPlayed' in value) || value['gamesPlayed'] === undefined) return false
  if (!('bestScore' in value) || value['bestScore'] === undefined) return false
  if (!('averageScore' in value) || value['averageScore'] === undefined) return false
  if (!('hasPlayedDailyChallenge' in value) || value['hasPlayedDailyChallenge'] === undefined)
    return false
  if (!('distanceUnit' in value) || value['distanceUnit'] === undefined) return false
  return true
}

export function GetMe200ResponseFromJSON(json: any): GetMe200Response {
  return GetMe200ResponseFromJSONTyped(json, false)
}

export function GetMe200ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): GetMe200Response {
  if (json == null) {
    return json
  }
  return {
    id: json['id'],
    name: json['name'],
    avatarEmoji: json['avatar_emoji'],
    avatarBg: json['avatar_bg'],
    gamesPlayed: json['games_played'],
    bestScore: json['best_score'],
    averageScore: json['average_score'],
    hasPlayedDailyChallenge: json['has_played_daily_challenge'],
    distanceUnit: json['distance_unit'],
  }
}

export function GetMe200ResponseToJSON(json: any): GetMe200Response {
  return GetMe200ResponseToJSONTyped(json, false)
}

export function GetMe200ResponseToJSONTyped(
  value?: GetMe200Response | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    id: value['id'],
    name: value['name'],
    avatar_emoji: value['avatarEmoji'],
    avatar_bg: value['avatarBg'],
    games_played: value['gamesPlayed'],
    best_score: value['bestScore'],
    average_score: value['averageScore'],
    has_played_daily_challenge: value['hasPlayedDailyChallenge'],
    distance_unit: value['distanceUnit'],
  }
}
