/* tslint:disable */
/* eslint-disable */
/**
 * Geoguess Lite
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
/**
 *
 * @export
 * @interface GetMeDefaultResponse
 */
export interface GetMeDefaultResponse {
  /**
   *
   * @type {string}
   * @memberof GetMeDefaultResponse
   */
  message: string
}

/**
 * Check if a given object implements the GetMeDefaultResponse interface.
 */
export function instanceOfGetMeDefaultResponse(value: object): value is GetMeDefaultResponse {
  if (!('message' in value) || value['message'] === undefined) return false
  return true
}

export function GetMeDefaultResponseFromJSON(json: any): GetMeDefaultResponse {
  return GetMeDefaultResponseFromJSONTyped(json, false)
}

export function GetMeDefaultResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): GetMeDefaultResponse {
  if (json == null) {
    return json
  }
  return {
    message: json['message'],
  }
}

export function GetMeDefaultResponseToJSON(json: any): GetMeDefaultResponse {
  return GetMeDefaultResponseToJSONTyped(json, false)
}

export function GetMeDefaultResponseToJSONTyped(
  value?: GetMeDefaultResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    message: value['message'],
  }
}
