/* tslint:disable */
/* eslint-disable */
/**
 * Geoguess Lite
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
import type { GetTodayTopScores200ResponseScoresInner } from './GetTodayTopScores200ResponseScoresInner'
import {
  GetTodayTopScores200ResponseScoresInnerFromJSON,
  GetTodayTopScores200ResponseScoresInnerFromJSONTyped,
  GetTodayTopScores200ResponseScoresInnerToJSON,
  GetTodayTopScores200ResponseScoresInnerToJSONTyped,
} from './GetTodayTopScores200ResponseScoresInner'

/**
 *
 * @export
 * @interface GetTodayTopScores200Response
 */
export interface GetTodayTopScores200Response {
  /**
   *
   * @type {Array<GetTodayTopScores200ResponseScoresInner>}
   * @memberof GetTodayTopScores200Response
   */
  scores: Array<GetTodayTopScores200ResponseScoresInner>
}

/**
 * Check if a given object implements the GetTodayTopScores200Response interface.
 */
export function instanceOfGetTodayTopScores200Response(
  value: object,
): value is GetTodayTopScores200Response {
  if (!('scores' in value) || value['scores'] === undefined) return false
  return true
}

export function GetTodayTopScores200ResponseFromJSON(json: any): GetTodayTopScores200Response {
  return GetTodayTopScores200ResponseFromJSONTyped(json, false)
}

export function GetTodayTopScores200ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): GetTodayTopScores200Response {
  if (json == null) {
    return json
  }
  return {
    scores: (json['scores'] as Array<any>).map(GetTodayTopScores200ResponseScoresInnerFromJSON),
  }
}

export function GetTodayTopScores200ResponseToJSON(json: any): GetTodayTopScores200Response {
  return GetTodayTopScores200ResponseToJSONTyped(json, false)
}

export function GetTodayTopScores200ResponseToJSONTyped(
  value?: GetTodayTopScores200Response | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    scores: (value['scores'] as Array<any>).map(GetTodayTopScores200ResponseScoresInnerToJSON),
  }
}
