/* tslint:disable */
/* eslint-disable */
/**
 * Geoguess Lite
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
import type { GetTodayChallenge200ResponseRoundsInner } from './GetTodayChallenge200ResponseRoundsInner'
import {
  GetTodayChallenge200ResponseRoundsInnerFromJSON,
  GetTodayChallenge200ResponseRoundsInnerFromJSONTyped,
  GetTodayChallenge200ResponseRoundsInnerToJSON,
  GetTodayChallenge200ResponseRoundsInnerToJSONTyped,
} from './GetTodayChallenge200ResponseRoundsInner'

/**
 *
 * @export
 * @interface GetTodayChallenge200Response
 */
export interface GetTodayChallenge200Response {
  /**
   *
   * @type {Date}
   * @memberof GetTodayChallenge200Response
   */
  date: Date
  /**
   *
   * @type {Array<GetTodayChallenge200ResponseRoundsInner>}
   * @memberof GetTodayChallenge200Response
   */
  rounds: Array<GetTodayChallenge200ResponseRoundsInner>
}

/**
 * Check if a given object implements the GetTodayChallenge200Response interface.
 */
export function instanceOfGetTodayChallenge200Response(
  value: object,
): value is GetTodayChallenge200Response {
  if (!('date' in value) || value['date'] === undefined) return false
  if (!('rounds' in value) || value['rounds'] === undefined) return false
  return true
}

export function GetTodayChallenge200ResponseFromJSON(json: any): GetTodayChallenge200Response {
  return GetTodayChallenge200ResponseFromJSONTyped(json, false)
}

export function GetTodayChallenge200ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): GetTodayChallenge200Response {
  if (json == null) {
    return json
  }
  return {
    date: new Date(json['date']),
    rounds: (json['rounds'] as Array<any>).map(GetTodayChallenge200ResponseRoundsInnerFromJSON),
  }
}

export function GetTodayChallenge200ResponseToJSON(json: any): GetTodayChallenge200Response {
  return GetTodayChallenge200ResponseToJSONTyped(json, false)
}

export function GetTodayChallenge200ResponseToJSONTyped(
  value?: GetTodayChallenge200Response | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    date: value['date'].toISOString().substring(0, 10),
    rounds: (value['rounds'] as Array<any>).map(GetTodayChallenge200ResponseRoundsInnerToJSON),
  }
}
