/* tslint:disable */
/* eslint-disable */
/**
 * Geoguess Lite
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
/**
 *
 * @export
 * @interface GetTodayChallenge200ResponseRoundsInner
 */
export interface GetTodayChallenge200ResponseRoundsInner {
  /**
   *
   * @type {number}
   * @memberof GetTodayChallenge200ResponseRoundsInner
   */
  round: number
  /**
   *
   * @type {string}
   * @memberof GetTodayChallenge200ResponseRoundsInner
   */
  imageId: string
}

/**
 * Check if a given object implements the GetTodayChallenge200ResponseRoundsInner interface.
 */
export function instanceOfGetTodayChallenge200ResponseRoundsInner(
  value: object,
): value is GetTodayChallenge200ResponseRoundsInner {
  if (!('round' in value) || value['round'] === undefined) return false
  if (!('imageId' in value) || value['imageId'] === undefined) return false
  return true
}

export function GetTodayChallenge200ResponseRoundsInnerFromJSON(
  json: any,
): GetTodayChallenge200ResponseRoundsInner {
  return GetTodayChallenge200ResponseRoundsInnerFromJSONTyped(json, false)
}

export function GetTodayChallenge200ResponseRoundsInnerFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): GetTodayChallenge200ResponseRoundsInner {
  if (json == null) {
    return json
  }
  return {
    round: json['round'],
    imageId: json['image_id'],
  }
}

export function GetTodayChallenge200ResponseRoundsInnerToJSON(
  json: any,
): GetTodayChallenge200ResponseRoundsInner {
  return GetTodayChallenge200ResponseRoundsInnerToJSONTyped(json, false)
}

export function GetTodayChallenge200ResponseRoundsInnerToJSONTyped(
  value?: GetTodayChallenge200ResponseRoundsInner | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    round: value['round'],
    image_id: value['imageId'],
  }
}
