/* tslint:disable */
/* eslint-disable */
/**
 * Geoguess Lite
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
/**
 *
 * @export
 * @interface Image
 */
export interface Image {
  /**
   *
   * @type {string}
   * @memberof Image
   */
  id: string
  /**
   *
   * @type {boolean}
   * @memberof Image
   */
  isPano: boolean
}

/**
 * Check if a given object implements the Image interface.
 */
export function instanceOfImage(value: object): value is Image {
  if (!('id' in value) || value['id'] === undefined) return false
  if (!('isPano' in value) || value['isPano'] === undefined) return false
  return true
}

export function ImageFromJSON(json: any): Image {
  return ImageFromJSONTyped(json, false)
}

export function ImageFromJSONTyped(json: any, ignoreDiscriminator: boolean): Image {
  if (json == null) {
    return json
  }
  return {
    id: json['id'],
    isPano: json['is_pano'],
  }
}

export function ImageToJSON(json: any): Image {
  return ImageToJSONTyped(json, false)
}

export function ImageToJSONTyped(value?: Image | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value
  }

  return {
    id: value['id'],
    is_pano: value['isPano'],
  }
}
