/* tslint:disable */
/* eslint-disable */
/**
 * Geoguess Lite
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
import type { GetImages200ResponseImagesInner } from './GetImages200ResponseImagesInner'
import {
  GetImages200ResponseImagesInnerFromJSON,
  GetImages200ResponseImagesInnerFromJSONTyped,
  GetImages200ResponseImagesInnerToJSON,
  GetImages200ResponseImagesInnerToJSONTyped,
} from './GetImages200ResponseImagesInner'

/**
 *
 * @export
 * @interface ImagesResponse
 */
export interface ImagesResponse {
  /**
   *
   * @type {Array<GetImages200ResponseImagesInner>}
   * @memberof ImagesResponse
   */
  images: Array<GetImages200ResponseImagesInner>
}

/**
 * Check if a given object implements the ImagesResponse interface.
 */
export function instanceOfImagesResponse(value: object): value is ImagesResponse {
  if (!('images' in value) || value['images'] === undefined) return false
  return true
}

export function ImagesResponseFromJSON(json: any): ImagesResponse {
  return ImagesResponseFromJSONTyped(json, false)
}

export function ImagesResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ImagesResponse {
  if (json == null) {
    return json
  }
  return {
    images: (json['images'] as Array<any>).map(GetImages200ResponseImagesInnerFromJSON),
  }
}

export function ImagesResponseToJSON(json: any): ImagesResponse {
  return ImagesResponseToJSONTyped(json, false)
}

export function ImagesResponseToJSONTyped(
  value?: ImagesResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    images: (value['images'] as Array<any>).map(GetImages200ResponseImagesInnerToJSON),
  }
}
