/* tslint:disable */
/* eslint-disable */
/**
 * Geoguess Lite
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
import type { GetTodayTopScores200ResponseScoresInner } from './GetTodayTopScores200ResponseScoresInner'
import {
  GetTodayTopScores200ResponseScoresInnerFromJSON,
  GetTodayTopScores200ResponseScoresInnerFromJSONTyped,
  GetTodayTopScores200ResponseScoresInnerToJSON,
  GetTodayTopScores200ResponseScoresInnerToJSONTyped,
} from './GetTodayTopScores200ResponseScoresInner'

/**
 *
 * @export
 * @interface TopDailyScores
 */
export interface TopDailyScores {
  /**
   *
   * @type {Array<GetTodayTopScores200ResponseScoresInner>}
   * @memberof TopDailyScores
   */
  scores: Array<GetTodayTopScores200ResponseScoresInner>
}

/**
 * Check if a given object implements the TopDailyScores interface.
 */
export function instanceOfTopDailyScores(value: object): value is TopDailyScores {
  if (!('scores' in value) || value['scores'] === undefined) return false
  return true
}

export function TopDailyScoresFromJSON(json: any): TopDailyScores {
  return TopDailyScoresFromJSONTyped(json, false)
}

export function TopDailyScoresFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): TopDailyScores {
  if (json == null) {
    return json
  }
  return {
    scores: (json['scores'] as Array<any>).map(GetTodayTopScores200ResponseScoresInnerFromJSON),
  }
}

export function TopDailyScoresToJSON(json: any): TopDailyScores {
  return TopDailyScoresToJSONTyped(json, false)
}

export function TopDailyScoresToJSONTyped(
  value?: TopDailyScores | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    scores: (value['scores'] as Array<any>).map(GetTodayTopScores200ResponseScoresInnerToJSON),
  }
}
