/* tslint:disable */
/* eslint-disable */
/**
 * Geoguess Lite
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
/**
 *
 * @export
 * @interface UpdateMeRequest
 */
export interface UpdateMeRequest {
  /**
   *
   * @type {string}
   * @memberof UpdateMeRequest
   */
  name?: string
  /**
   *
   * @type {string}
   * @memberof UpdateMeRequest
   */
  avatarEmoji?: string
  /**
   *
   * @type {string}
   * @memberof UpdateMeRequest
   */
  avatarBg?: string
  /**
   *
   * @type {number}
   * @memberof UpdateMeRequest
   */
  gamesPlayed?: number
  /**
   *
   * @type {number}
   * @memberof UpdateMeRequest
   */
  bestScore?: number
  /**
   *
   * @type {number}
   * @memberof UpdateMeRequest
   */
  averageScore?: number
  /**
   * Preferred distance unit
   * @type {string}
   * @memberof UpdateMeRequest
   */
  distanceUnit?: UpdateMeRequestDistanceUnitEnum
}

/**
 * @export
 */
export const UpdateMeRequestDistanceUnitEnum = {
  Km: 'km',
  Mile: 'mile',
} as const
export type UpdateMeRequestDistanceUnitEnum =
  (typeof UpdateMeRequestDistanceUnitEnum)[keyof typeof UpdateMeRequestDistanceUnitEnum]

/**
 * Check if a given object implements the UpdateMeRequest interface.
 */
export function instanceOfUpdateMeRequest(value: object): value is UpdateMeRequest {
  return true
}

export function UpdateMeRequestFromJSON(json: any): UpdateMeRequest {
  return UpdateMeRequestFromJSONTyped(json, false)
}

export function UpdateMeRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): UpdateMeRequest {
  if (json == null) {
    return json
  }
  return {
    name: json['name'] == null ? undefined : json['name'],
    avatarEmoji: json['avatar_emoji'] == null ? undefined : json['avatar_emoji'],
    avatarBg: json['avatar_bg'] == null ? undefined : json['avatar_bg'],
    gamesPlayed: json['games_played'] == null ? undefined : json['games_played'],
    bestScore: json['best_score'] == null ? undefined : json['best_score'],
    averageScore: json['average_score'] == null ? undefined : json['average_score'],
    distanceUnit: json['distance_unit'] == null ? undefined : json['distance_unit'],
  }
}

export function UpdateMeRequestToJSON(json: any): UpdateMeRequest {
  return UpdateMeRequestToJSONTyped(json, false)
}

export function UpdateMeRequestToJSONTyped(
  value?: UpdateMeRequest | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    name: value['name'],
    avatar_emoji: value['avatarEmoji'],
    avatar_bg: value['avatarBg'],
    games_played: value['gamesPlayed'],
    best_score: value['bestScore'],
    average_score: value['averageScore'],
    distance_unit: value['distanceUnit'],
  }
}
