/* tslint:disable */
/* eslint-disable */
/**
 * Geoguess Lite
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
/**
 *
 * @export
 * @interface UpdateDailyScoreRequest
 */
export interface UpdateDailyScoreRequest {
  /**
   *
   * @type {number}
   * @memberof UpdateDailyScoreRequest
   */
  score?: number
  /**
   *
   * @type {number}
   * @memberof UpdateDailyScoreRequest
   */
  distance?: number
  /**
   *
   * @type {number}
   * @memberof UpdateDailyScoreRequest
   */
  timeTaken?: number
}

/**
 * Check if a given object implements the UpdateDailyScoreRequest interface.
 */
export function instanceOfUpdateDailyScoreRequest(value: object): value is UpdateDailyScoreRequest {
  return true
}

export function UpdateDailyScoreRequestFromJSON(json: any): UpdateDailyScoreRequest {
  return UpdateDailyScoreRequestFromJSONTyped(json, false)
}

export function UpdateDailyScoreRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): UpdateDailyScoreRequest {
  if (json == null) {
    return json
  }
  return {
    score: json['score'] == null ? undefined : json['score'],
    distance: json['distance'] == null ? undefined : json['distance'],
    timeTaken: json['time_taken'] == null ? undefined : json['time_taken'],
  }
}

export function UpdateDailyScoreRequestToJSON(json: any): UpdateDailyScoreRequest {
  return UpdateDailyScoreRequestToJSONTyped(json, false)
}

export function UpdateDailyScoreRequestToJSONTyped(
  value?: UpdateDailyScoreRequest | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    score: value['score'],
    distance: value['distance'],
    time_taken: value['timeTaken'],
  }
}
