/* tslint:disable */
/* eslint-disable */
/**
 * Geoguess Lite
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
/**
 *
 * @export
 * @interface User
 */
export interface User {
  /**
   *
   * @type {string}
   * @memberof User
   */
  id: string
  /**
   *
   * @type {string}
   * @memberof User
   */
  name: string
  /**
   *
   * @type {string}
   * @memberof User
   */
  avatarEmoji: string
  /**
   *
   * @type {string}
   * @memberof User
   */
  avatarBg: string
  /**
   *
   * @type {number}
   * @memberof User
   */
  gamesPlayed: number
  /**
   *
   * @type {number}
   * @memberof User
   */
  bestScore: number
  /**
   *
   * @type {number}
   * @memberof User
   */
  averageScore: number
  /**
   * Whether the user has played today's daily challenge
   * @type {boolean}
   * @memberof User
   */
  hasPlayedDailyChallenge: boolean
}

/**
 * Check if a given object implements the User interface.
 */
export function instanceOfUser(value: object): value is User {
  if (!('id' in value) || value['id'] === undefined) return false
  if (!('name' in value) || value['name'] === undefined) return false
  if (!('avatarEmoji' in value) || value['avatarEmoji'] === undefined) return false
  if (!('avatarBg' in value) || value['avatarBg'] === undefined) return false
  if (!('gamesPlayed' in value) || value['gamesPlayed'] === undefined) return false
  if (!('bestScore' in value) || value['bestScore'] === undefined) return false
  if (!('averageScore' in value) || value['averageScore'] === undefined) return false
  if (!('hasPlayedDailyChallenge' in value) || value['hasPlayedDailyChallenge'] === undefined)
    return false
  return true
}

export function UserFromJSON(json: any): User {
  return UserFromJSONTyped(json, false)
}

export function UserFromJSONTyped(json: any, ignoreDiscriminator: boolean): User {
  if (json == null) {
    return json
  }
  return {
    id: json['id'],
    name: json['name'],
    avatarEmoji: json['avatar_emoji'],
    avatarBg: json['avatar_bg'],
    gamesPlayed: json['games_played'],
    bestScore: json['best_score'],
    averageScore: json['average_score'],
    hasPlayedDailyChallenge: json['has_played_daily_challenge'],
  }
}

export function UserToJSON(json: any): User {
  return UserToJSONTyped(json, false)
}

export function UserToJSONTyped(value?: User | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value
  }

  return {
    id: value['id'],
    name: value['name'],
    avatar_emoji: value['avatarEmoji'],
    avatar_bg: value['avatarBg'],
    games_played: value['gamesPlayed'],
    best_score: value['bestScore'],
    average_score: value['averageScore'],
    has_played_daily_challenge: value['hasPlayedDailyChallenge'],
  }
}
