/* tslint:disable */
/* eslint-disable */
/**
 * Geoguess Lite
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime'
import type {
  CreateDailyScoreRequest,
  GetMeDefaultResponse,
  GetTodayTopScores200Response,
  GetTodayTopScores200ResponseScoresInner,
} from '../models/index'
import {
  CreateDailyScoreRequestFromJSON,
  CreateDailyScoreRequestToJSON,
  GetMeDefaultResponseFromJSON,
  GetMeDefaultResponseToJSON,
  GetTodayTopScores200ResponseFromJSON,
  GetTodayTopScores200ResponseToJSON,
  GetTodayTopScores200ResponseScoresInnerFromJSON,
  GetTodayTopScores200ResponseScoresInnerToJSON,
} from '../models/index'

export interface CreateDailyScoreOperationRequest {
  createDailyScoreRequest: CreateDailyScoreRequest
}

/**
 *
 */
export class DailyScoresApi extends runtime.BaseAPI {
  /**
   * Submit daily score record
   */
  async createDailyScoreRaw(
    requestParameters: CreateDailyScoreOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<GetTodayTopScores200ResponseScoresInner>> {
    if (requestParameters['createDailyScoreRequest'] == null) {
      throw new runtime.RequiredError(
        'createDailyScoreRequest',
        'Required parameter "createDailyScoreRequest" was null or undefined when calling createDailyScore().',
      )
    }

    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    headerParameters['Content-Type'] = 'application/json'

    let urlPath = `/daily-scores`

    const response = await this.request(
      {
        path: urlPath,
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
        body: CreateDailyScoreRequestToJSON(requestParameters['createDailyScoreRequest']),
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      GetTodayTopScores200ResponseScoresInnerFromJSON(jsonValue),
    )
  }

  /**
   * Submit daily score record
   */
  async createDailyScore(
    requestParameters: CreateDailyScoreOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<GetTodayTopScores200ResponseScoresInner> {
    const response = await this.createDailyScoreRaw(requestParameters, initOverrides)
    return await response.value()
  }

  /**
   * Get top 5 daily scores for today
   */
  async getTodayTopScoresRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<GetTodayTopScores200Response>> {
    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    let urlPath = `/daily-scores`

    const response = await this.request(
      {
        path: urlPath,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      GetTodayTopScores200ResponseFromJSON(jsonValue),
    )
  }

  /**
   * Get top 5 daily scores for today
   */
  async getTodayTopScores(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<GetTodayTopScores200Response> {
    const response = await this.getTodayTopScoresRaw(initOverrides)
    return await response.value()
  }
}
