/* tslint:disable */
/* eslint-disable */
/**
 * Geoguess Lite
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime'
import type { GetMeDefaultResponse, GetTodayChallenge200Response } from '../models/index'
import {
  GetMeDefaultResponseFromJSON,
  GetMeDefaultResponseToJSON,
  GetTodayChallenge200ResponseFromJSON,
  GetTodayChallenge200ResponseToJSON,
} from '../models/index'

/**
 *
 */
export class DailyChallengesApi extends runtime.BaseAPI {
  /**
   * Get today\'s daily challenge
   */
  async getTodayChallengeRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<GetTodayChallenge200Response>> {
    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    let urlPath = `/daily-challenges/today`

    const response = await this.request(
      {
        path: urlPath,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      GetTodayChallenge200ResponseFromJSON(jsonValue),
    )
  }

  /**
   * Get today\'s daily challenge
   */
  async getTodayChallenge(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<GetTodayChallenge200Response> {
    const response = await this.getTodayChallengeRaw(initOverrides)
    return await response.value()
  }
}
