/* tslint:disable */
/* eslint-disable */
/**
 * Geoguess Lite
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime'
import type { GetImages200Response, GetMeDefaultResponse } from '../models/index'
import {
  GetImages200ResponseFromJSON,
  GetImages200ResponseToJSON,
  GetMeDefaultResponseFromJSON,
  GetMeDefaultResponseToJSON,
} from '../models/index'

export interface GetImagesRequest {
  isPano?: boolean
}

/**
 *
 */
export class ImagesApi extends runtime.BaseAPI {
  /**
   * Get random images for game rounds
   */
  async getImagesRaw(
    requestParameters: GetImagesRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<GetImages200Response>> {
    const queryParameters: any = {}

    if (requestParameters['isPano'] != null) {
      queryParameters['is_pano'] = requestParameters['isPano']
    }

    const headerParameters: runtime.HTTPHeaders = {}

    let urlPath = `/images`

    const response = await this.request(
      {
        path: urlPath,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      GetImages200ResponseFromJSON(jsonValue),
    )
  }

  /**
   * Get random images for game rounds
   */
  async getImages(
    requestParameters: GetImagesRequest = {},
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<GetImages200Response> {
    const response = await this.getImagesRaw(requestParameters, initOverrides)
    return await response.value()
  }
}
