/* tslint:disable */
/* eslint-disable */
/**
 * Geoguess Lite
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime'
import type {
  CreateMultiplayerRounds200Response,
  CreateMultiplayerRoundsRequest,
  GetMeDefaultResponse,
} from '../models/index'
import {
  CreateMultiplayerRounds200ResponseFromJSON,
  CreateMultiplayerRounds200ResponseToJSON,
  CreateMultiplayerRoundsRequestFromJSON,
  CreateMultiplayerRoundsRequestToJSON,
  GetMeDefaultResponseFromJSON,
  GetMeDefaultResponseToJSON,
} from '../models/index'

export interface CreateMultiplayerRoundsOperationRequest {
  createMultiplayerRoundsRequest: CreateMultiplayerRoundsRequest
}

/**
 *
 */
export class MultiplayerRoundsApi extends runtime.BaseAPI {
  /**
   * Create multiplayer rounds
   */
  async createMultiplayerRoundsRaw(
    requestParameters: CreateMultiplayerRoundsOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<CreateMultiplayerRounds200Response>> {
    if (requestParameters['createMultiplayerRoundsRequest'] == null) {
      throw new runtime.RequiredError(
        'createMultiplayerRoundsRequest',
        'Required parameter "createMultiplayerRoundsRequest" was null or undefined when calling createMultiplayerRounds().',
      )
    }

    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    headerParameters['Content-Type'] = 'application/json'

    let urlPath = `/multiplayer-rounds`

    const response = await this.request(
      {
        path: urlPath,
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
        body: CreateMultiplayerRoundsRequestToJSON(
          requestParameters['createMultiplayerRoundsRequest'],
        ),
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      CreateMultiplayerRounds200ResponseFromJSON(jsonValue),
    )
  }

  /**
   * Create multiplayer rounds
   */
  async createMultiplayerRounds(
    requestParameters: CreateMultiplayerRoundsOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<CreateMultiplayerRounds200Response> {
    const response = await this.createMultiplayerRoundsRaw(requestParameters, initOverrides)
    return await response.value()
  }
}
