AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  geoguess-lite-api

  Sample SAM Template for geoguess-lite-api

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Api:
    Cors:
      AllowMethods: "'*'"
      AllowHeaders: "'Accept, Accept-Encoding, Accept-Language, Authorization, Connection, Host, Origin, Referer, Sec-Fetch-Dest, Sec-Fetch-Mode, Sec-Fetch-Site, User-Agent'"
      AllowOrigin: "'*'"
  Function:
    Timeout: 30
    Environment:
      Variables:
        POWERTOOLS_SERVICE_NAME: geoguess-lite-api
        POWERTOOLS_LOG_LEVEL: INFO
    # @see: https://docs.aws.amazon.com/powertools/python/latest/#lambda-layer
    Layers:
      - !Sub arn:aws:lambda:ap-northeast-1:017000801446:layer:AWSLambdaPowertoolsPythonV3-python314-x86_64:27

Parameters:
  Environment:
    Type: String
    AllowedValues:
      - localstack
      - dev
      - prod
    Default: localstack
  SecretArn:
    Type: String

Resources:
  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref Environment
      Auth:
        DefaultAuthorizer: FirebaseAuthorizer
        Authorizers:
          FirebaseAuthorizer:
            FunctionArn: !GetAtt FirebaseAuthFunction.Arn
            Identity:
              Headers:
                - Authorization

  FirebaseAuthFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: core.auth.lambda_handler
      Runtime: python3.14
      Architectures:
        - x86_64
      Environment:
        Variables:
          Environment: !Ref Environment
      Policies:
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: !Ref SecretArn

  HealthCheckFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: health.handler.lambda_handler
      Runtime: python3.14
      Architectures:
        - x86_64
      Environment:
        Variables:
          Environment: !Ref Environment
      Policies:
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: !Ref SecretArn
      Events:
        HealthCheck:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /health
            Method: get

  UsersFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: users.handler.lambda_handler
      Runtime: python3.14
      Architectures:
        - x86_64
      Environment:
        Variables:
          Environment: !Ref Environment
      Policies:
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: !Ref SecretArn
      Events:
        UsersApi:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /users
            Method: post
