AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  geoguess-lite-api

  Sample SAM Template for geoguess-lite-api

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Parameters:
  Environment:
    Type: String
    AllowedValues:
      - localstack
      - dev
      - prod
    Default: localstack

Resources:
  HealthCheckFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: functions.ping.lambda_handler
      Runtime: python3.14
      Architectures:
        - x86_64
      Environment:
        Variables:
          Environment: !Ref Environment
      Events:
        HealthCheck:
          Type: Api
          Properties:
            Path: /ping
            Method: get

Outputs:
  HealthCheckApi:
    Description: "API Gateway endpoint URL for Prod stage for Health Check function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}/Prod/ping/"
  HealthCheckFunction:
    Description: "Health Check Lambda Function ARN"
    Value: !GetAtt HealthCheckFunction.Arn
  HealthCheckFunctionIamRole:
    Description: "Implicit IAM Role created for Health Check function"
    Value: !GetAtt HealthCheckFunctionRole.Arn
